language: java
part_one: |
  Senju no hate. Todokazaru yami no mite, utsurazaru ten no ite.  
  Hikari o otosu michi, hidane o aoru kaze, tsudoite madō na, waga yubi o miyo.  
  Kōdan, hasshin, kujō, tenkei, shippō, tairin, haiiro no hōtō.  
  Yumihiku kanata, kōkō toshite kiyu.
part_two: |
  Nijimidasu kondaku no monshō. Fusonnaru kyōki no utsuwa.  
  Waki agari, hitei shi, shibire, matataki, nemuri o samatageru.  
  Hakōsuru tetsu no ōjo. Taezu jikaisuru doro no ningyō.   
  Ketsugōseyo, hanpatsuseyo. Chi ni michi onore no muryoku o shire
